version: '3.8'

services:
  mysql:
    image: mysql:8.0 
    container_name: hr-mysql
    restart: always
    ports:
      - "3306:3306" # Map MySQL port to host
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: hr            # Default database
    volumes:
      - hr_data:/var/lib/hr       # Persistent storage for MySQL data

volumes:
  hr_data:
